### ISSUE TITLE
Ошибка 403 при клейме тасков

### ISSUE THREAD

**Issue by Nord1cWarr1or** [YarmolenkoD/boinkers#1]
```
Failed to claim reward for twitterQuotePost39. Status code: 403
````

**Comment by YarmolenkoD** [comment]
> ```
> Failed to claim reward for twitterQuotePost39. Status code: 403
> ```

Спасибо, буду смотреть в чем может быть проблема

**Comment by Nord1cWarr1or** [comment]
Ну она не на всех тасках, а где-то на 30%, может быть там специальные условия какие-то и не может выполнить

**Comment by YarmolenkoD** [comment]
> Ну она не на всех тасках, а где-то на 30%, может быть там специальные условия какие-то и не может выполнить

Постараюсь сегодня разобраться, есть догадки в чем причина, спасибо за отзыв, да одна из причин это специальные условия и время через которое можно клеймить после того как выполнил задание

**Comment by YarmolenkoD** [comment]
> Ну она не на всех тасках, а где-то на 30%, может быть там специальные условия какие-то и не может выполнить

Запушил фиксы, добавил некоторые таски в черный список и пофиксил выполнение других, плюс просмотр рекламы теперь работает стабильно

**Comment by Nord1cWarr1or** [comment]
Спасибо, пока ошибок нет
