### ISSUE TITLE
Playpiggypiggy2 error

### ISSUE THREAD

**Issue by fnursandi** [YarmolenkoD/boinkers#3]
![image](https://github.com/user-attachments/assets/7b19d1af-4d5c-4534-b7ab-7dc5f14830c5)
This my feedback, can u fix it?

**Comment by YarmolenkoD** [comment]
@fnursandi Everything works correctly

**Comment by YarmolenkoD** [comment]
@fnursandi We cannot finish some tasks with script. I added the task to black list for now.
