### ISSUE TITLE
slot machine

### ISSUE THREAD

**Issue by M-Majed** [YarmolenkoD/boinkers#4]
spin_user = await self.get_user_info(http_client=http_client)
                    spins = spin_user['gamesEnergy']['slotMachine']['energy']
it returns 0 even though it has 50 spins

**Comment by YarmolenkoD** [comment]
@M-Majed ok, thanks, will check it when will have time

**Comment by M-Majed** [comment]
> @M-Majed ok, thanks, will check it when will have time

https://github.com/icerplusplus/boinkers_tool_claim
this guys tool returns the correct value in case you haven't found the problem yet

also there is a value in users data which is called isSus
you can add it to the code so if it's true then perform emergency stop
just a suggestion

**Comment by YarmolenkoD** [comment]
@M-Majed thank you !

**Comment by YarmolenkoD** [comment]
@M-Majed Fixed
