### ISSUE TITLE
Options for Booster & Toggle for auto spin 

### ISSUE THREAD

**Issue by PocaBBQ** [YarmolenkoD/boinkers#5]
can you make expand to these functions?
Like option to claim others booster except for the free one (like the 30 energy cost booster)
And option to turn off auto spin (for saving energy to claim energy booster)

**Comment by YarmolenkoD** [comment]
@PocaBBQ 

Added this env variables.

ENABLE_AUTO_TASKS=False
ENABLE_AUTO_WHEEL_FORTUNE=False
ENABLE_AUTO_ELEVATOR=False
ENABLE_AUTO_SPIN=False
ENABLE_AUTO_UPGRADE=False
